apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mysql
  name: trillian-mysql
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/component: mysql
  sessionAffinity: None
