schema: olm.composite.catalogs
catalogs:
  - name: "4.13" 
    destination:
      baseImage: registry.redhat.io/openshift4/ose-operator-registry:v4.13 
      workingDir: .
    builders:
      - olm.builder.basic
  - name: "4.12"
    destination:
      baseImage: registry.redhat.io/openshift4/ose-operator-registry:v4.12
      workingDir: .
    builders:
      - olm.builder.basic