# permissions for end users to edit ctlogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ctlog-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rhtas-operator
    app.kubernetes.io/part-of: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: ctlog-editor-role
rules:
- apiGroups:
  - rhtas.redhat.com
  resources:
  - ctlogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhtas.redhat.com
  resources:
  - ctlogs/status
  verbs:
  - get
