# permissions for end users to edit trillians.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trillian-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rhtas-operator
    app.kubernetes.io/part-of: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: trillian-editor-role
rules:
- apiGroups:
  - rhtas.redhat.com
  resources:
  - trillians
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhtas.redhat.com
  resources:
  - trillians/status
  verbs:
  - get
