kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
      endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /var/lib/kubelet/config.json
      # this is the path in gh action where the config is saved
      hostPath: /tmp/config.json
