apiVersion: rhtas.redhat.com/v1alpha1
kind: Rekor
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: rekor-sample
spec:
  rekor:
    external: true
    keySecret: rekor-private-key
    rekorCert:
      create: true
