apiVersion: rhtas.redhat.com/v1alpha1
kind: Fulcio
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: fulcio-sample
spec:
  fulcio:
    external: true
    keySecret: fulcio-secret-rh
    oidcIssuers:
      "https://your-oidc-issuer-url":
        ClientID: "trusted-artifact-signer"
        IssuerURL: "https://your-oidc-issuer-url"
        Type: "email"
