apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: securesign-sample
spec:
  rekor:
    externalAccess:
      enabled: true
    certificate:
      create: true
      secretName: rekor-cert
    monitoring: false
  trillian:
    database:
      create: true
  fulcio:
    externalAccess:
      enabled: true
    keySecret: fulcio-secret-rh
    config:
      OIDCIssuers:
        "https://your-oidc-issuer-url":
          ClientID: "trusted-artifact-signer"
          IssuerURL: "https://your-oidc-issuer-url"
          Type: "email"
    certificate:
      create: true
      organizationName: Red Hat
      organizationEmail: jdoe@redhat.com
      secretName: fulcio-cert
    monitoring: false
  tuf:
    externalAccess:
      enabled: true
